routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
	return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/yuran', 'yuranController@index');
Route::get('/pay_yuran', 'yuranController@pay_yuran');

Route::resource('students', 'StudentController');
Route::get('/add_student_form', 'StudentController@open_form');
Route::post('/add_student_form', 'StudentController@save_form');
Route::get('/list_student', 'StudentController@list');

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model {
	//
	protected $fillable = [
		'namapelajar', 'bin', 'namaayah', 'kelas', 'notelefonrumah',
	];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/guru.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class guru extends Model
{
    //
}

app/murid.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class murid extends Model
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Student;
use Illuminate\Http\Request;

class StudentController extends Controller {
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		//
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request) {
		//
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id) {
		//
		$student = Student::where('id', $id)
			->get();

		return view('student.show', compact('student'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id) {
		//
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id) {
		//
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id) {
		//
	}

	public function open_form() {

		return view('student.register_student');
	}

	public function save_form(Request $request) {
		//

		// dd($request);
		$request->validate([
			'namapelajar' => 'required',
			'namaayah' => 'required',
			'kelas' => 'required',
			'notelefonrumah' => 'required',
		]);
		// dd($request->all());

		try {
			Student::create($request->all());
		} catch (Exception $e) {
			echo 'Caught exception: ', $e->getMessage(), "\n";
		}

		return redirect()->route('student.list')
			->with('success', 'Student added successfully.');

	}

	public function list() {
		$students = Student::all();

		return view('student.list', compact('students'));
	}

}

app/Http/Controllers/yuranController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class yuranController extends Controller {
	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index() {
		//
		return view('yuran.index');
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {
		//
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @return \Illuminate\Http\Response
	 */
	public function store(Request $request) {
		//
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id) {
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function edit($id) {
		//
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request  $request
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function update(Request $request, $id) {
		//
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function destroy($id) {
		//
	}

	public function pay_yuran() {
		return view('yuran.register_yuran');
	}
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/footer.blade.php
<div class="footer" style="background-color: transparent; ">
	<span style="font-size: 14px;">Copyright © 2019 Perbadanan Usahawan Nasional Berhad</span>

	<input type="hidden" name="revertUrlPrevious" id="revertUrlPrevious" value="{{url()->previous()}}">
	{{--<p>KL Sentral</p>--}}
</div>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=11">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>MyYuran</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">


    <link rel="stylesheet" href="{{ URL::asset('css/style.css') }}">

    <link href="{{ URL::asset('font-awesome/css/all.css')}}" rel="stylesheet">
</head>
<body>
    <div id="current_path" style="display: none; font-size: 50px;">{{Request::path()}}</div>
    <div class="wrapper d-flex align-items-stretch">
        @include('layouts.sidebar')
        @yield('content')
    </div>
    @include('layouts.footer')

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="{{ URL::asset('js/main.js') }}"></script>
    <script type="text/javascript">
        $(document).ready(function() {

        });
    </script>
</body>
</html>

resources/views/layouts/sidebar.blade.php
<nav id="sidebar">
        <div class="p-4 pt-5">
          <a href="#" class="img logo rounded-circle mb-5" style="background-image: url({{ URL::asset('img/teacher_logo.jpg') }});"></a>
          <ul class="list-unstyled components mb-5">
            <li class="active">
              <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Home</a>
              <ul class="collapse list-unstyled" id="homeSubmenu">
                <li>
                    <a href="#">Home 1</a>
                </li>
                <li>
                    <a href="#">Home 2</a>
                </li>
                <li>
                    <a href="#">Home 3</a>
                </li>
              </ul>
            </li>
            <li>
                <a href="#">About</a>
            </li>
            <li>
              <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Pelajar</a>
              <ul class="collapse list-unstyled" id="pageSubmenu">
                <li>
                    <a href="/list_student">Senarai pelajar</a>
                </li>
                <li>
                    <a href="/add_student_form">Tambah pelajar</a>
                </li>
              </ul>
            </li>
            <li>
              <a href="/pay_yuran">Yuran</a>
            </li>
          </ul>

          <div class="footer">
            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib.com</a>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>

        </div>
      </nav>

resources/views/student/list.blade.php
@extends('layouts.master')

@section('content')

<div id="content" class="p-4 p-md-5">
        <h2 class="mb-4">Senarai pelajar</h2>
<div class="container mt-2">
<div class="bs-example container" data-example-id="striped-table">
  <table class="table table-striped table-bordered table-hover">

    <thead>
      <tr>
        <th>#</th>
        <th>Nama pelajar</th>
        <th>Kelas</th>
        <th>No tel. rumah</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    @foreach($students as $student)
      <tr>
      	<td>{{$student->id}}</td>
        <td>{{$student->namapelajar}} {{ $student->bin }} {{ $student->namaayah}}</td>
        <td>{{$student->kelas}}</td>
        <td>{{$student->notelefonrumah}}</td>
        {{-- <td><a class="btn btn-sm btn-primary" name="" value="edit" href="/">Edit</a></td> --}}
        <td>
            {{-- <form action="{{ route('students.destroy',$student->id) }}" method="POST"> --}}

                <a class="btn btn-sm btn-info" href="{{ route('students.show',$student->id) }}"><i class="fas fa-edit"></i></a>

                {{-- <a class="btn btn-sm btn-primary" href="{{ route('students.edit',$student->id) }}">Edit</a>
				<a class='btn btn-info btn-xs' href="{{ route('students.show',$student->id) }}"><span class="glyphicon glyphicon-edit"></span></a>
                @csrf
                @method('DELETE')

                <button type="submit" class="btn btn-sm btn-danger">Delete</button> --}}
            {{-- </form> --}}
        </td>
      </tr>
    @endforeach

    </tbody>
  </table>
</div>
</div>
</div>
@endsection

resources/views/student/register_student.blade.php
@extends('layouts.master')

@section('content')
 <!-- Page Content  -->
      <div id="content" class="p-4 p-md-5">
        <h2 class="mb-4">Daftar pelajar</h2>

        <div class="container">
  <form action="/add_student_form" method="POST">
    @csrf

    <div class="row">
      <div class="col-md-5">
        <div class="form-group">
          <label for="first">Nama pelajar</label>
          <input type="text" class="form-control" placeholder="" id="input_namapelajar" name="namapelajar">
        </div>
      </div>
      <!--  col-md-6   -->
        <div class="col-md-2">
            <div class="form-group">
              <label for="Gender" class="select">Bin/Binti</label>
              <select class="form-control" id="selectinput_bin" name="bin">
                  <option value="bin">bin</option>
                  <option value="binti">binti</option>
                </select>
            </div>
        </div>

      <div class="col-md-5">
        <div class="form-group">
          <label for="last">Nama ayah</label>
          <input type="text" class="form-control" placeholder="" id="input_namaayah" name="namaayah">
        </div>
      </div>
      <!--  col-md-6   -->



    </div>


    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <label for="kelas">Kelas</label>
          <input type="text" class="form-control" placeholder="" id="input_kelas" name="kelas">
        </div>


      </div>
      <!--  col-md-6   -->

      <div class="col-md-6">

        <div class="form-group">
          <label for="phone">No telefon rumah</label>
          <input type="tel" class="form-control" id="input_notelefonrumah" placeholder="" name="notelefonrumah">
        </div>
      </div>
      <!--  col-md-6   -->
    </div>
    <!--  row   -->


    <div class="row">
      <div class="col-md-6">

        <div class="form-group">
          <label for="email">Email address</label>
          <input type="email" class="form-control" id="email" placeholder="" name="email">
        </div>
      </div>
      <!--  col-md-6   -->

      <div class="col-md-6">
        <div class="form-group">

        </div>

      </div>
      <!--  col-md-6   -->
    </div>
    <!--  row   -->

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>

      </div>

@endsection

resources/views/student/show.blade.php
@extends('layouts.master')

@section('content')

<div id="content" class="p-4 p-md-5">
        <h2 class="mb-4">Maklumat pelajar</h2>
<div class="container mt-2">
<div class="container">
  <div class="row">
    <div class="col-7 col-sm-7 col-md-7 col-lg-7">
      <div class="card">
      	<div class="col-5 col-sm-5 col-md-5 col-lg-5">
	        <img class="card-img" src="https://png.pngtree.com/png-clipart/20190618/original/pngtree-school-student-illustration-student-pencil-male-student-hand-drawn-illustration-cartoon-png-image_3932877.jpg" alt="Vans">
	        <div class="card-img-overlay d-flex justify-content-end">
	          <a href="#" class="card-link text-danger like">
	            <i class="fas fa-heart"></i>
	          </a>
	        </div>
    	</div>
        <div class="card-body">
          <h4 class="card-title">{{$student[0]->namapelajar}}</h4>
          <h6 class="card-subtitle mb-2 text-muted">Kelas: {{$student[0]->kelas}}</h6>
          <h6 class="card-subtitle mb-2 text-muted">No tel rumah: {{$student[0]->notelefonrumah}}</h6>
          <p class="card-text">
            The Vans All-Weather MTE Collection features footwear and apparel designed to withstand the elements whilst still looking cool.             </p>


        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>
@endsection

resources/views/yuran/index.blade.php
@extends('layouts.master')

@section('content')
 <!-- Page Content  -->
      <div id="content" class="p-4 p-md-5">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">

            <button type="button" id="sidebarCollapse" class="btn btn-primary">
              <i class="fa fa-bars"></i>
              <span class="sr-only">Toggle Menu</span>
            </button>
            <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-bars"></i>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="nav navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Portfolio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>

        <h2 class="mb-4">Sidebar #01</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>

@endsection

resources/views/yuran/register_yuran.blade.php
@extends('layouts.master')

@section('content')
 <!-- Page Content  -->
      <div id="content" class="p-4 p-md-5">
        <h2 class="mb-4">Daftar pembayaran pelajar</h2>

        <div class="container">
  <form>

    <div class="row">
      <div class="col-md-5">
        <div class="form-group">
          <label for="first">Nama pelajar</label>
          <input type="text" class="form-control" placeholder="" id="input_namapelajar">
        </div>
      </div>
      <!--  col-md-6   -->
        <div class="col-md-2">
            <div class="form-group">
              <label for="Gender" class="select">Bin/Binti</label>
              <select class="form-control" id="selectinput_bin">
                  <option>Bin</option>
                  <option>Binti</option>
                </select>
            </div>
        </div>

      <div class="col-md-5">
        <div class="form-group">
          <label for="last">Nama ayah</label>
          <input type="text" class="form-control" placeholder="" id="input_namaayah">
        </div>
      </div>
      <!--  col-md-6   -->



    </div>


    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <label for="kelas">Kelas</label>
          <input type="text" class="form-control" placeholder="" id="input_kelas">
        </div>


      </div>
      <!--  col-md-6   -->

      <div class="col-md-6">

        <div class="form-group">
          <label for="phone">No telefon rumah</label>
          <input type="tel" class="form-control" id="input_notelefonrumah" placeholder="phone">
        </div>
      </div>
      <!--  col-md-6   -->
    </div>
    <!--  row   -->


    <div class="row">
      <div class="col-md-6">

        <div class="form-group">
          <label for="email">Email address</label>
          <input type="email" class="form-control" id="email" placeholder="email">
        </div>
      </div>
      <!--  col-md-6   -->

      <div class="col-md-6">
        <div class="form-group">
          <label for="url">Your Website <small>Please include http://</small></label>
          <input type="url" class="form-control" id="url" placeholder="url">
        </div>

      </div>
      <!--  col-md-6   -->
    </div>
    <!--  row   -->


    <label for="contact-preference">When is the best time of day to reach you?</label>
    <div class="radio">
      <label>
        <input type="radio" name="contact-preference" id="contact-preference" value="am" checked>Morning
      </label>
    </div>
    <div class="radio">
      <label>
        <input type="radio" name="contact-preference" id="contact-preference" value="pm" checked>Evening
      </label>
    </div>

    <label for="newsletter">Would you like to recieve our email newsletter?</label>
    <div class="checkbox">

      <label>
        <input type="checkbox" value="Sure!" id="newsletter"> Sure!
      </label>
    </div>


    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>

      </div>

@endsection